### PR TITLE
Another prefix related update:

### PR DESCRIPTION
**Pull request by mark-cooper**
The digital load code path is a backend request so revert the insertion
of frontend prefix.

### CODE REVIEW

**Comment by bobbi-SMR** [comment]
Hey, Mark,

Since I don't have a setup with proxies, I'm kinda relying on you to have tested this thoroughly; did the previous pull request not work, or is there something different about 2.5.* ?

**Comment by mark-cooper** [comment]
Hi Bobbi. I'm in a somewhat similar position to you in that I'm not really a user of this plugin and my involvement is solely for getting it to work for others, so I'm limited in what exactly I can test directly (both in terms of time and knowledge of the functionality). All reports are that everything is working fine, with the exception of the digital object import under a prefix. I've corrected for that, it has been tested and verified by other users for archival objects and digital objects. I believe that covers both import paths provided by the plugin so I'm not anticipating the need for any additional prefix related updates after this.

**Comment by bobbi-SMR** [comment]
Accepted, version will be updated.

**Comment by bobbi-SMR** [comment]
really merged this time :-)

**Pull request merged**
